meta_product_name: "Crash Pad"
meta_title: "Crash Pad  - Welcome"
meta_description: "Crash Pad a website that allows you to book a room or property anywhere in the world. Book a room for one night or longer"
meta_image: "carousel1.jpg" # should exist in `app/assets/images/`
